/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { GetServerSideProps } from "next"
import YouTube from 'react-youtube';

import Layout from "@/layout/Layout"
import Overview from "@/components/Overview";
import Starring from "@/components/Starring";
import Recommendations from "@/components/Recommendations";
import Similar from '@/components/Similar';
import axios from 'axios';
import { useState } from 'react';
import Trailer from '@/components/Trailer';
import Companies from '@/components/Сompanies';
import RecMovies from '@/components/RecMovies';

interface IMovieProps {
	actors: any
	details: any
	similar: any
	recommendations: any
	videos: any
	external: any
}

const key = "1bb078d910403b47ba1478583d67aa0b"
let url = 'https://api.themoviedb.org/3/movie/'

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
	const movie_id = query.id

	const credits = await fetch(`${url}${movie_id}/credits?api_key=${key}&language=en-US`)
	const actors = await credits.json()

	const resspons = await fetch(`${url}${movie_id}?api_key=${key}&language=en-US`)
	const details = await resspons.json()

	const resspons3 = await fetch(`${url}${movie_id}/similar?api_key=${key}&language=en-US&page=1`)
	const similar = await resspons3.json()

	const resspons4 = await fetch(`${url}${movie_id}/recommendations?api_key=${key}&language=en-US&page=1`)
	const recommendations = await resspons4.json()

	const resspons5 = await fetch(`${url}${movie_id}/reviews?api_key=${key}&language=en-US&page=1`)
	const reviews = await resspons5.json()

	const video = await fetch(`${url}${movie_id}/videos?api_key=${key}&append_to_response=videos&language=en-US`)
	const video2 = await video.json()

	const external_ids = await fetch(`https://api.themoviedb.org/3/movie/${movie_id}/external_ids?api_key=${key}`)
	const external = await external_ids.json()

	return {
		props: {
			actors: actors,
			details: details,
			similar: similar.results,
			recommendations: recommendations.results,
			reviews: reviews,
			videos: video2,
			external: external
		}
	}
}

const Movie: React.FC<IMovieProps> = ({ actors, details, similar, recommendations, videos, external }) => {

	return (
		<>
			<Head>
				<title>Netflix | {details?.title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<section>
					<Overview details={details} external={external} />
				</section>
				<section>
					<Companies details={details} />
				</section>
				<section>
					<Starring actors={actors} />
				</section>
				<section>
					<RecMovies movies={recommendations} description={'Recommended films'} />
				</section>
				<section>
					<Trailer videos={videos} />
				</section>
				<section>
					<RecMovies movies={similar} description={'Sequels and Prequels'} />
				</section>
			</Layout>
		</>
	);
}

export default Movie