/* eslint-disable @next/next/no-img-element */

import { useState, useEffect } from 'react';
import Image from 'next/image';
import Layout from '@/layout/Layout';
import Movie from '@/components/children/Movie';

import { IMoviesPageProps } from '@/types/pages/moviespage';

import { RxHamburgerMenu } from "react-icons/rx"
import { IoMdClose } from "react-icons/io";
import Head from 'next/head';
import AllMovies from '@/components/AllMovies';

export const getStaticProps = async () => {
	const key = "1bb078d910403b47ba1478583d67aa0b"

	const res = await fetch(`https://api.themoviedb.org/3/movie/upcoming?api_key=${key}&language=en-US&page=1`)
	const movies = await res.json()

	const response = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=${key}&language=en-US&page=1`)
	const popular = await response.json()

	const now_playing = await fetch(`https://api.themoviedb.org/3/movie/now_playing?api_key=${key}&language=en-US&page=1`)
	const nowPlaying = await now_playing.json()

	const top_rated = await fetch(`https://api.themoviedb.org/3/movie/top_rated?api_key=${key}&language=en-US&page=1`)
	const topRated = await top_rated.json()

	return {
		props: {
			movies: movies.results,
			popular: popular.results,
			nowPlaying: nowPlaying.results,
			topRated: topRated.results
		}
	}
}

const Movies: React.FC<IMoviesPageProps> = ({ movies, popular, nowPlaying, topRated }) => {
	const [imgSrc, setImgSrc] = useState('')
	const random = Math.floor(Math.random() * 20);
	const [burger, setBurger] = useState(false)
	let pk = "w-3/5 max-xl:w-4/5 max-lg:w-full max-md:h-screen || max-xl:mt-5 max-md:mt-0 || max-md:fixed max-md:-top-full max-md:bg-black/30 ease-out duration-300"
	let mb = "w-3/5 max-xl:w-4/5 max-lg:w-full max-md:h-screen || max-xl:mt-5 max-md:mt-0 || z-50 max-md:fixed max-md:top-0 max-md:left-0 max-md:backdrop-blur-sm max-md:bg-black/30 ease-out duration-300"

	useEffect(() => {
		if (typeof window !== undefined) {
			setImgSrc(`https://www.themoviedb.org/t/p/w1920_and_h800_multi_faces${movies[random]?.backdrop_path}`)
		}
	}, [movies, random])

	return (
		<Layout>
			<Head>
				<title>Netflix | Movies</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="absolute top-0 left-0 z-[-1] opacity-30">
				<img className="w-screen h-screen object-cover ease-in duration-100" src={imgSrc} alt="movie" />
				<div className="absolute left-0 bottom-0 w-full h-full bg-gradient-to-t from-[#1e2538] to-transparent"></div>
			</div>
			<section>
				<AllMovies description={'Now in cinema'} movies={movies} />
			</section>
			<section>
				<AllMovies description={'Most Popular'} movies={topRated} />
			</section>
			<section>
				<AllMovies description={'Popular films'} movies={popular} />
			</section>
			<section>
				<AllMovies description={'Now playing'} movies={nowPlaying} />
			</section>
		</Layout>
	)
};

export default Movies;