import Layout from '@/layout/Layout';
import People from '@/components/children/People';
import Head from 'next/head';
import { IActorsPageProps } from '@/types/pages/actorspage';

export const getStaticProps = async () => {
	const key = "1bb078d910403b47ba1478583d67aa0b"

	const person = await fetch(`https://api.themoviedb.org/3/person/popular?api_key=${key}&language=en-US&page=1`)
	const persons = await person.json()

	return {
		props: {
			persons: persons.results,
		}
	}
}

interface IActorsProps {
	persons: [
		{
			id: number
			name: string
			character: string
			job: string
			profile_path: string | null
			roles: any
			jobs: any
		}
	]
}

const Actors: React.FC<IActorsPageProps> = ({ persons }) => {

	return (
		<Layout>
			<Head>
				<title>Netflix | Actors</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<div className="flex max-xl:flex-col justify-between items-center max-xl:items-start">
					<div className="max-md:w-full flex items-center max-md:justify-center max-md:gap-5">
						<h1 className='text-6xl max-xl:text-4xl max-md:text-2xl || font-black text-white'>Popular actors</h1>
					</div>
				</div>
				<div className="grid grid-cols-4 max-lg:grid-cols-3 max-md:grid-cols-2 || gap-5 max-md:gap-x-2 max-md:gap-y-4 || pt-12 max-lg:pt-7 max-md:pt-5 max-sm:pt-4">
					{
						persons.map((item: {
							id: number
							name: string
							character: string
							job: string
							profile_path: string | null
							roles: any
							jobs: any
						}) =>
							<People key={item.id} item={item} />
						)
					}
				</div>
			</div>
		</Layout>
	)
};

export default Actors;