/* eslint-disable @next/next/no-img-element */
import { useState, useEffect } from 'react';

import Layout from '@/layout/Layout';
import Movie from '@/components/children/Movie';
import Head from 'next/head';

interface ISeriesProps {
	TV: any
	TVPopular: any
	TVOn_the_air: any
	TVAiring_today: any
}

export const getStaticProps = async () => {
	const key = "1bb078d910403b47ba1478583d67aa0b"

	const top_rated = await fetch(`https://api.themoviedb.org/3/tv/top_rated?api_key=${key}&language=en-US&page=1`)
	const TV = await top_rated.json()

	const popular = await fetch(`https://api.themoviedb.org/3/tv/popular?api_key=${key}&language=en-US&page=1`)
	const TVPopular = await popular.json()

	const on_the_air = await fetch(`https://api.themoviedb.org/3/tv/on_the_air?api_key=${key}&language=en-US&page=1`)
	const TVOn_the_air = await on_the_air.json()

	const airing_today = await fetch(`https://api.themoviedb.org/3/tv/airing_today?api_key=${key}&language=en-US&page=1`)
	const TVAiring_today = await airing_today.json()

	return {
		props: {
			TV: TV.results,
			TVPopular: TVPopular.results,
			TVOn_the_air: TVOn_the_air.results,
			TVAiring_today: TVAiring_today.results
		}
	}
}

const Series: React.FC<ISeriesProps> = ({ TV, TVPopular, TVOn_the_air, TVAiring_today }) => {

	console.log(TV);

	const [imgSrc, setImgSrc] = useState('')
	const random = Math.floor(Math.random() * 20);

	useEffect(() => {
		if (typeof window !== undefined) {
			setImgSrc(`https://www.themoviedb.org/t/p/w1920_and_h800_multi_faces${TV[random]?.backdrop_path}`)
		}
	}, [])

	return (
		<>
			<Head>
				<title>Netflix | Series</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className="absolute top-0 left-0 z-[-1] opacity-30">
					<img className="w-screen h-screen object-cover ease-in duration-100" src={imgSrc} alt="movie" />
					<div className="absolute left-0 bottom-0 w-full h-full bg-gradient-to-t from-[#1e2538] to-transparent"></div>
				</div>
				<section>
					<div className=''>
						<div className="flex max-xl:flex-col justify-between items-center max-xl:items-start">
							<div className="max-md:w-full flex items-center max-md:justify-center max-md:gap-5">
								<h1 className='text-4xl max-xl:text-3xl max-md:text-xl || font-black text-white'>Самые популярные сериалы</h1>
							</div>
						</div>
						<div className="grid grid-cols-4 max-lg:grid-cols-3 max-md:grid-cols-2 || gap-5 max-md:gap-x-2 max-md:gap-y-4 || pt-12 max-lg:pt-7 max-md:pt-5 max-sm:pt-4">
							{
								TV.map((item: { id: any; }) => <Movie key={item.id} item={item} />)
							}
						</div>
					</div>
				</section>
				<section>
					<div className='mt-32 max-xl:mt-24 max-lg:mt-16 max-md:mt-10 max-sm:mt-8'>
						<div className="flex max-xl:flex-col justify-between items-center max-xl:items-start">
							<div className="max-md:w-full flex items-center max-md:justify-center max-md:gap-5">
								<h1 className='text-4xl max-xl:text-3xl max-md:text-xl || font-black text-white'>Популярные сериалы</h1>
							</div>
						</div>
						<div className="grid grid-cols-4 max-lg:grid-cols-3 max-md:grid-cols-2 || gap-5 max-md:gap-x-2 max-md:gap-y-4 || pt-12 max-lg:pt-7 max-md:pt-5 max-sm:pt-4">
							{
								TVPopular.map((item: { id: any; }) => <Movie key={item.id} item={item} />)
							}
						</div>
					</div>
				</section>
				<section>
					<div className='mt-32 max-xl:mt-24 max-lg:mt-16 max-md:mt-10 max-sm:mt-8'>
						<div className="flex max-xl:flex-col justify-between items-center max-xl:items-start">
							<div className="max-md:w-full flex items-center max-md:justify-center max-md:gap-5">
								<h1 className='text-4xl max-xl:text-3xl max-md:text-xl || font-black text-white'>в эфире</h1>
							</div>
						</div>
						<div className="grid grid-cols-4 max-lg:grid-cols-3 max-md:grid-cols-2 || gap-5 max-md:gap-x-2 max-md:gap-y-4 || pt-12 max-lg:pt-7 max-md:pt-5 max-sm:pt-4">
							{
								TVOn_the_air.map((item: { id: any; }) => <Movie key={item.id} item={item} />)
							}
						</div>
					</div>
				</section>
				<section>
					<div className='mt-32 max-xl:mt-24 max-lg:mt-16 max-md:mt-10 max-sm:mt-8'>
						<div className="flex max-xl:flex-col justify-between items-center max-xl:items-start">
							<div className="max-md:w-full flex items-center max-md:justify-center max-md:gap-5">
								<h1 className='text-4xl max-xl:text-3xl max-md:text-xl || font-black text-white'>Сегодня в эфире</h1>
							</div>
						</div>
						<div className="grid grid-cols-4 max-lg:grid-cols-3 max-md:grid-cols-2 || gap-5 max-md:gap-x-2 max-md:gap-y-4 || pt-12 max-lg:pt-7 max-md:pt-5 max-sm:pt-4">
							{
								TVAiring_today.map((item: { id: any; }) => <Movie key={item.id} item={item} />)
							}
						</div>
					</div>
				</section>
			</Layout>
		</>
	)
};

export default Series;