/* eslint-disable @next/next/no-img-element */
import { useState, useEffect } from 'react';

import Layout from '@/layout/Layout';
import Movie from '@/components/children/Movie';
import Head from 'next/head';
import { useHttp } from '@/hook/http.hook';
import { ISeriesPageProps } from '@/types/pages/seriespage';
import AllMovies from '@/components/AllMovies';

export const getStaticProps = async () => {
	const key: string = "1bb078d910403b47ba1478583d67aa0b"
	const URL: string = "https://api.themoviedb.org/3/"

	const top_rated = await fetch(`${URL}tv/top_rated?api_key=${key}&language=en-US&page=1`)
	const TV = await top_rated.json()

	const popular = await fetch(`${URL}tv/popular?api_key=${key}&language=en-US&page=1`)
	const TVPopular = await popular.json()

	const on_the_air = await fetch(`${URL}tv/on_the_air?api_key=${key}&language=en-US&page=1`)
	const TVOn_the_air = await on_the_air.json()

	const airing_today = await fetch(`${URL}tv/airing_today?api_key=${key}&language=en-US&page=1`)
	const TVAiring_today = await airing_today.json()

	return {
		props: {
			TV: TV.results,
			TVPopular: TVPopular.results,
			TVOn_the_air: TVOn_the_air.results,
			TVAiring_today: TVAiring_today.results
		}
	}
}

const Series: React.FC<ISeriesPageProps> = ({ TV, TVPopular, TVOn_the_air, TVAiring_today }) => {
	const { loading, error, request } = useHttp();

	const [imgSrc, setImgSrc] = useState('')
	const random = Math.floor(Math.random() * 20);

	useEffect(() => {
		if (typeof window !== undefined) {
			setImgSrc(`https://www.themoviedb.org/t/p/w1920_and_h800_multi_faces${TV[random]?.backdrop_path}`)
		}
	}, [TV, random])

	if (loading) {
		return <span className='text-9xl text-red-600 absolute top-0 left-0 z-50'>loading</span>;
	}
	if (error) {
		return <span>error</span>;
	}

	return (
		<>
			<Head>
				<title>Netflix | Series</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<div className="absolute top-0 left-0 z-[-1] opacity-30">
					<img className="w-screen h-screen object-cover ease-in duration-100" src={imgSrc} alt="movie" />
					<div className="absolute left-0 bottom-0 w-full h-full bg-gradient-to-t from-[#1e2538] to-transparent"></div>
				</div>
				<section>
					<AllMovies movies={TV} description={'Most Popular TV Series'} />
				</section>
				<section>
					<AllMovies movies={TVPopular} description={'Popular TV shows'} />
				</section>
				<section>
					<AllMovies movies={TVOn_the_air} description={'On the air'} />
				</section>
				<section>
					<AllMovies movies={TVAiring_today} description={'On air today'} />
				</section>
			</Layout>
		</>
	)
};

export default Series;